apiVersion: apps/v1
kind: Deployment
metadata:
  name: dfms-management-master
  namespace: test
  labels:
    app: dfms-management-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dfms-management-master
  # Pod template
  template:
    metadata:
      namespace: test
      labels:
        app: dfms-management-master
        commit: _VERSION_
    spec:
      containers:
      - name: dfms-management-master
        image: dfmscloud/dfms-management:master
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: dfms-management-master
  namespace: test
  labels:
    app: dfms-management-master
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
      app: dfms-management-master